Models/ErrorViewModel.cs
namespace Virtueel_Huisdier.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Game.cs
namespace Virtueel_Huisdier.Models;

public class Game
{
    public int id { get; set; }
    public string name { get; set; }
    public string dier { get; set; }
    public string gif { get; set; }
    public Status status { get; set; }

    public Game()
    {
        status = new Status()
        {
            gezondheid = 100,
            eten = 80,
            geluk = 50,
            energie = 60
        };
    }
}

public class Status
{
    public int gezondheid { get; set; }
    public int eten { get; set; }
    public int geluk { get; set; }
    public int energie { get; set; }
}

Models/Huisdier.cs
namespace Virtueel_Huisdier.Models
{
    public class Huisdier
    {
        public string Name { get; set; }
        public string ImageUrl { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Virtueel_Huisdier.Models;

namespace Virtueel_Huisdier.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HuisdierController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using System.Text.Json;
using System.IO;
using Virtueel_Huisdier.Models;
using System.Globalization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Reflection.Emit;
using System.Web;
using System.Timers;

namespace Virtueel_Huisdier.Controllers
{
    public class HuisdierController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {
            return RedirectToAction("Game");
        }

        [HttpPost]
        public ActionResult SaveImg(Game game)
        {
            string dier = game.dier;
            return RedirectToAction("Name", game);
        }

        public IActionResult Name(Game game)
        {
            return View("Name", game);
        }

        [HttpPost]
        public ActionResult SaveName(Game game)
        {
            string name = game.name;
            string dier = game.dier;

            var updatedFile = JsonSerializer.Serialize(game);
            System.IO.File.WriteAllText("./game.json", updatedFile);

            return RedirectToAction("Game", game);
        }
        public IActionResult Game(Game game)
        {
            if (System.IO.File.Exists("./game.json"))
            {
                var file = System.IO.File.ReadAllText("./game.json");
                game = JsonSerializer.Deserialize<Game>(file);
            }

            if (!System.IO.File.Exists("./game.json") && game != null)
            {
                var file = JsonSerializer.Serialize(game);
                System.IO.File.WriteAllText("./game.json", file);
                return View("Index");
            }

            game.status.energie -= 1;
            game.status.eten -= 3;
            game.status.geluk -= 1;
            game.gif = TempData["Gif"]?.ToString() ?? "";

            if (game.status.energie <= -10 || game.status.eten <= -10 || game.status.geluk <= -10)
            {
                System.IO.File.Delete("./game.json");
                return View("GameOver");
            }

            var updatedFile = JsonSerializer.Serialize(game);
            System.IO.File.WriteAllText("./game.json", updatedFile);

            return View("Game", game);
        }
        public IActionResult DeleteGame()
        {
            System.IO.File.Delete("./game.json");
            return View("Index");
        }

        [HttpPost]
        public IActionResult Feed(Game game)
        {
            TempData["Gif"] = game.gif;

            var file = System.IO.File.ReadAllText("./game.json");
            if (string.IsNullOrWhiteSpace(file))
                return Redirect(nameof(Index));

            if (file == null)
                return Redirect(nameof(Index));


            game = JsonSerializer.Deserialize<Game>(file);
            if (game == null)
                return Redirect(nameof(Index));

            game.status.eten += 10;
            game.status.gezondheid -= 5;
            game.status.geluk += 2;
            game.status.energie -= 3;

            if (game.status.energie > 100) { game.status.energie = 100; }
            if (game.status.eten > 100) { game.status.eten = 100; }
            if (game.status.geluk > 100) { game.status.geluk = 100; }
            if (game.status.gezondheid > 100) { game.status.gezondheid = 100; }

            var updatedFile = JsonSerializer.Serialize(game);
            System.IO.File.WriteAllText("./game.json", updatedFile);

            return RedirectToAction("Game");
        }

        [HttpPost]
        public IActionResult Play(Game game)
        {
            TempData["Gif"] = game.gif;
            var file = System.IO.File.ReadAllText("./game.json");
            var model = JsonSerializer.Deserialize<Game>(file);

            model.status.eten -= 5;
            model.status.gezondheid += 3;
            model.status.geluk += 10;
            model.status.energie -= 6;

            if (model.status.energie > 100) { model.status.energie = 100; }
            if (model.status.eten > 100) { model.status.eten = 100; }
            if (model.status.geluk > 100) { model.status.geluk = 100; }
            if (model.status.gezondheid > 100) { model.status.gezondheid = 100; }

            var updatedFile = JsonSerializer.Serialize(model);
            System.IO.File.WriteAllText("./game.json", updatedFile);

            return RedirectToAction("Game");
        }

        [HttpPost]
        public IActionResult Sleep(Game game)
        {
            TempData["Gif"] = game.gif;
            var file = System.IO.File.ReadAllText("./game.json");
            var model = JsonSerializer.Deserialize<Game>(file);

            model.status.energie += 10;
            model.status.eten -= 2;
            model.status.geluk -= 2;
            model.status.gezondheid += 5;

            if (model.status.energie > 100) { model.status.energie = 100; }
            if (model.status.eten > 100) { model.status.eten = 100; }
            if (model.status.geluk > 100) { model.status.geluk = 100; }
            if (model.status.gezondheid > 100) { model.status.gezondheid = 100; }

            var updatedFile = JsonSerializer.Serialize(model);
            System.IO.File.WriteAllText("./game.json", updatedFile);

            return RedirectToAction("Game");
        }

        [HttpPost]
        public IActionResult Medicine(Game game)
        {
            TempData["Gif"] = game.gif;
            var file = System.IO.File.ReadAllText("./game.json");
            var model = JsonSerializer.Deserialize<Game>(file);

            model.status.energie += 1;
            model.status.eten += 1;
            model.status.geluk += 1;
            model.status.gezondheid += 10;

            if (model.status.energie > 100) { model.status.energie = 100; }
            if (model.status.eten > 100) { model.status.eten = 100; }
            if (model.status.geluk > 100) { model.status.geluk = 100; }
            if (model.status.gezondheid > 100) { model.status.gezondheid = 100; }

            var updatedFile = JsonSerializer.Serialize(model);
            System.IO.File.WriteAllText("./game.json", updatedFile);

            return RedirectToAction("Game");
        }

        [HttpPost]
        public ActionResult HandleForm(string yesNo)
        {
            if (yesNo == "Ja")
            {
                return RedirectToAction("Game");
            }
            else if (yesNo == "Nee")
            {
                ViewBag.Result = "Klik dan op het kruisje!!!";
            }
            return View("GameOver");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Huisdier/Game.cshtml
@model Virtueel_Huisdier.Models.Game

<link rel="stylesheet" type="text/css" href="~/css/game.css" />
<link rel="stylesheet" type="text/css" href="~/css/popup.css" />

<div id="balkje">
    <div class="groote">
        <form method="post" action="@Url.Action("DeleteGame", "Huisdier")">
            <button type="submit" class="img-button">
                <img src="~/images/huis.jpg" />
            </button>
        </form>
    </div>
    <div id="progress">
        <img src="~/images/bot.jpg" />
        <p>@Model.status.eten</p>
    </div>
    <div id="progress">
        <img src="~/images/pl.jpg" />
        <p>@Model.status.gezondheid</p>
    </div>
    <div id="progress">
        <img src="~/images/sm.jpg" />
        <p>@Model.status.geluk</p>
    </div>
    <div id="progress">
        <img src="~/images/zzz.jpg" />
        <p>@Model.status.energie</p>
    </div>
    <div id="naam">
        <h2>@Model.name</h2>
    </div>
    <br /><br /><br />
</div>

<div style="display: inline-block;" class="size">
    <br />
    <form method="post" action="@Url.Action("Feed", "Huisdier")">
        <input type="hidden" name="gif" value="/images/hamstereat.gif" />
        <button type="submit" class="img-button">
            <img src="~/images/bot.jpg" />
        </button>
    </form>
    <form method="post" action="@Url.Action("Medicine", "Huisdier")">
        <input type="hidden" name="gif" value="/images/sickbunny.gif" />
        <button type="submit" class="img-button">
            <img src="~/images/pl.jpg" />
        </button>
    </form>
    <form method="post" action="@Url.Action("Play", "Huisdier")">
        <input type="hidden" name="gif" value="/images/birdplay.gif" />
        <button type="submit" class="img-button">
            <img src="~/images/sm.jpg" />
        </button>
    </form>
    <form method="post" action="@Url.Action("Sleep", "Huisdier")">
        <input type="hidden" name="gif" value="/images/sleepydog.gif" />
        <button type="submit" class="img-button">
            <img src="~/images/zzz.jpg" />
        </button>
    </form>
</div>

<img style="display: inline-block; max-block-size: 500px;" class="dier" src="@Model.dier" />

@if (!string.IsNullOrWhiteSpace(Model.gif))
{
    <div id="popup" style="display:none;">
        <img src="@Model.gif" />
    </div>
}

<script>
    function showPopupWithGif() {
        var popup = document.getElementById('popup');
        if (popup !== null) {
            popup.style.display = 'block';
            setTimeout(function () {
                popup.style.display = 'none';
            }, 4000);
        }
    }

    function gameLoop() {
        setTimeout(function () {
            window.location.reload();
        }, 4000);
    }

    window.onload = function () {
        showPopupWithGif();
        gameLoop();
    };
</script>

Views/Huisdier/GameOver.cshtml
<link rel="stylesheet" type="text/css" href="~/css/GameOver.css" />

<div class="size">
    <img class="p" src="~/images/GameOver.jpg" />
</div>

<div class="text">
    <h3>Wil je opnieuw beginnen? </h3><br />
</div>

<div class="content">
    <form method="post" action="@Url.Action("HandleForm", "Huisdier")">
        <input type="submit" name="yesNo" value="Ja" />
        <input type="submit" name="yesNo" value="Nee" />
    </form>
</div>
<br />
<div class="bag">
    @if (ViewBag.Result != null)
    {
        <h1>@ViewBag.Result</h1>
    }
</div>

<div class="gif">
    <img src="~/images/deadcat.gif" />
</div>

Views/Huisdier/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@model Virtueel_Huisdier.Models.Game
 
<link rel="stylesheet" type="text/css" href="~/css/choose.css" />
 
<div class="text">
    <h2>Kies je dier!!</h2>
</div>
 
<div class="size">
<br /><br />
    <div class="ingesprongen-tekst">
        <div style="display: inline-block;">
            @using (Html.BeginForm("SaveImg", "Huisdier", FormMethod.Post, new { entype = "multipart/from-data" }))
            {
                <input type="hidden" name="dier" value="/images/Konijntje.jpg" />
                <button type="submit" class="img-button">
                <img src="~/images/Konijntje.jpg" class="p" />
                </button>
            }
        </div>
        <div style="display: inline-block;">
            @using (Html.BeginForm("SaveImg", "Huisdier", FormMethod.Post, new { entype = "multipart/from-data" }))
            {
                <input type="hidden" name="dier" value="/images/Hondje.jpg" />
                <button type="submit" class="img-button">
                <img src="~/images/Hondje.jpg" class="p"/>
                </button>
            }
        </div>
        <div style="display: inline-block;">
            @using (Html.BeginForm("SaveImg", "Huisdier", FormMethod.Post, new { entype = "multipart/from-data" }))
            {
                <input type="hidden" name="dier" value="/images/Poesje.jpg" />
                <button type="submit" class="img-button">
                <img src="~/images/Poesje.jpg" class="p"/>
                </button>
            }
</div><br /><br />
</div>
    <div class="image">
        <div style="display: inline-block;">
            @using (Html.BeginForm("SaveImg", "Huisdier", FormMethod.Post, new { entype = "multipart/from-data" }))
            {
                <input type="hidden" name="dier" value="/images/Vogel.jpg" />
                <button type="submit" class="img-button">
                <img src="~/images/Vogel.jpg" class="p"/>
                </button>
            }
        </div>
        <div style="display: inline-block;">
            @using (Html.BeginForm("SaveImg", "Huisdier", FormMethod.Post, new { entype = "multipart/from-data" }))
            {
                <input type="hidden" name="dier" value="/images/Hamster.jpg" />
                <button type="submit" class="img-button">
                <img src="~/images/Hamster.jpg" class="p"/>
                </button>
            }
        </div>
    </div>
</div>

Views/Huisdier/Name.cshtml
@model Virtueel_Huisdier.Models.Game

<link rel="stylesheet" type="text/css" href="~/css/name.css" />

<form method="post" action="@Url.Action("Index", "Huisdier")">
    <input type="submit" value="Terug" />
</form>

<br />
<br />
<br />
<br />
<br />
<div class="box1">
    <h2>Voer een naam in voor je dier!</h2>
</div>
<br />
<br />

<div class="form">
    <form method="post" action="@Url.Action("SaveName", "Huisdier")">
        <input type="text" name="name" id="name" placeholder="Naam" />
        <input type="submit" value="Oké" />
        <input type="hidden" name="dier" value="@Model.dier" />
    </form>
    <br />
    <div id="size">
        <img src="@Model.dier" />
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Virtueel_Huisdier</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Virtueel_Huisdier.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Huisdier" asp-action="Index">Virtueel_Huisdier</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Huisdier" asp-action="Name">Naam</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Huisdier" asp-action="Game">Game</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>